name = "BiochemicalVisualization"
uuid = "00dfb448-20af-4b14-a659-f3892fa4f701"
authors = ["Andreas Hildebrandt <andreas.hildebrandt@uni-mainz.de> and contributors"]
version = "0.1.0"

[deps]
BiochemicalAlgorithms = "9d651bdf-8945-47d1-9188-34e269d8f7b5"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Deno_jll = "04572ae6-984a-583e-9378-9577a1c2574d"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MsgPack = "99f44e22-a591-53d1-9472-aa23ef4bd671"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
