name = "BiochemicalVisualization"
uuid = "00dfb448-20af-4b14-a659-f3892fa4f701"
authors = ["Andreas Hildebrandt <andreas.hildebrandt@uni-mainz.de> and contributors"]
version = "0.1.0"

[deps]
BiochemicalAlgorithms = "9d651bdf-8945-47d1-9188-34e269d8f7b5"

[compat]
BiochemicalAlgorithms = "0.1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
